{ pkgs, config, lib, ... }:

with lib;

let
  cfg = config.provisioning.clusterConfig;

  # Build a lookup script that maps hostname to node config
  nodeConfigScript = pkgs.writeShellScript "generate-cluster-config" ''
    set -eu -o pipefail

    HOSTNAME=$(hostname)

    case "$HOSTNAME" in
      ${concatStringsSep "\n      " (mapAttrsToList (name: node: ''
        ${name})
          CLUSTER_HOSTNAME="${node.hostname}"
          CLUSTER_NODE_ADDRESS="${node.address}"
          CLUSTER_NODE_SECONDARY_ADDRESS="${node.secondaryAddress}"
          ;;
      '') config.virtualisation.ganeti.nodes)}
      *)
        echo "ERROR: Unknown hostname '$HOSTNAME'" >&2
        echo "Known hosts: ${concatStringsSep ", " (attrNames config.virtualisation.ganeti.nodes)}" >&2
        exit 1
        ;;
    esac

    cat > /etc/default/cluster <<EOF
# Cluster configuration for node $HOSTNAME
# Auto-generated by provision-cluster-config.service
# Do not edit manually - changes will be overwritten on next boot

export CLUSTER_HOSTNAME="$CLUSTER_HOSTNAME"
export CLUSTER_NODE_ADDRESS="$CLUSTER_NODE_ADDRESS"
export CLUSTER_NODE_SECONDARY_ADDRESS="$CLUSTER_NODE_SECONDARY_ADDRESS"
EOF

    echo "Generated /etc/default/cluster for node $HOSTNAME"
    cat /etc/default/cluster
  '';

in
{
  options.provisioning.clusterConfig = {
    enable = mkEnableOption "enable provisioning of cluster configuration";
  };

  config = mkIf cfg.enable {
    systemd.services."provision-cluster-config" = {
      description = "Provision cluster configuration from hostname";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      path = with pkgs; [ coreutils inetutils ];
      script = ''
        ${nodeConfigScript}
      '';

      serviceConfig = {
        Type = "oneshot";
        User = "root";
        Group = "root";
        RemainAfterExit = true;
      };

      wantedBy = [ "multi-user.target" ];
    };

    # Ensure /etc/default directory exists
    systemd.tmpfiles.rules = [
      "d /etc/default 0755 root root -"
    ];
  };
}
